Models/Test.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Web_TracNghiem_HTSV.Models
{
    public class Test
    {
        public string TestId { get; set; }
        public string TestName { get; set; }

        public bool IsLocked { get; set; }
        public ICollection<Question> Questions { get; set; }
        public ICollection<TestResult> TestResults { get; set; }

    }
}

Models/TestViewModel.cs
namespace Web_TracNghiem_HTSV.Models
{
    public class TestViewModel
    {
        public string TestId { get; set; }
        public string TestName { get; set; }
        public bool IsTestTaken { get; set; }
        public bool IsLocked { get; set; } = true;
    }
}

Controllers/TestResultsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Web_TracNghiem_HTSV.Data;
using Web_TracNghiem_HTSV.Models;

namespace Web_TracNghiem_HTSV.Controllers
{
    [Authorize(Roles = "Administrators")]

    public class TestResultsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TestResultsController(ApplicationDbContext context)
        {
            _context = context;
        }


        // Phương thức kiểm tra xem người dùng đã làm bài kiểm tra chưa
/*        public async Task<IActionResult> HasUserTakenTest(string userId, string testId)
        {
            var testResult = await _context.TestResults
                .FirstOrDefaultAsync(tr => tr.UserId == userId && tr.TestId == testId);

            if (testResult != null)
            {
                return Json(new { hasTaken = true });
            }
            else
            {
                return Json(new { hasTaken = false });
            }
        }*/

            // GET: TestResults
            public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.TestResults.Include(t => t.Test).Include(t => t.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: TestResults/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testResult = await _context.TestResults
                .Include(t => t.Test)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.TestResultId == id);
            if (testResult == null)
            {
                return NotFound();
            }

            return View(testResult);
        }

        // GET: TestResults/Create
        public IActionResult Create()
        {
            ViewData["TestId"] = new SelectList(_context.Tests, "TestId", "TestId");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: TestResults/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TestResultId,UserId,TestId,QuestionId,SelectedAnswer,IsCorrect,SubmittedAt,TotalScore")] TestResult testResult)
        {
            if (ModelState.IsValid)
            {
                _context.Add(testResult);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TestId"] = new SelectList(_context.Tests, "TestId", "TestId", testResult.TestId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", testResult.UserId);
            return View(testResult);
        }

        // GET: TestResults/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testResult = await _context.TestResults.FindAsync(id);
            if (testResult == null)
            {
                return NotFound();
            }
            ViewData["TestId"] = new SelectList(_context.Tests, "TestId", "TestId", testResult.TestId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", testResult.UserId);
            return View(testResult);
        }

        // POST: TestResults/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("TestResultId,UserId,TestId,QuestionId,SelectedAnswer,IsCorrect,SubmittedAt,TotalScore")] TestResult testResult)
        {
            if (id != testResult.TestResultId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(testResult);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestResultExists(testResult.TestResultId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TestId"] = new SelectList(_context.Tests, "TestId", "TestId", testResult.TestId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", testResult.UserId);
            return View(testResult);
        }

        // GET: TestResults/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testResult = await _context.TestResults
                .Include(t => t.Test)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.TestResultId == id);
            if (testResult == null)
            {
                return NotFound();
            }

            return View(testResult);
        }

        // POST: TestResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var testResult = await _context.TestResults.FindAsync(id);
            if (testResult != null)
            {
                _context.TestResults.Remove(testResult);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestResultExists(string id)
        {
            return _context.TestResults.Any(e => e.TestResultId == id);
        }
        // Phương thức xóa tất cả TestResults theo UserId
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteByUser(string userId)
        {
            var userTestResults = _context.TestResults.Where(tr => tr.UserId == userId).ToList();
            if (userTestResults.Any())
            {
                _context.TestResults.RemoveRange(userTestResults);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Tests");
        }
    }
}

Controllers/TestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using MongoDB.Driver.Linq;
using System.Linq;
using System.Security.Claims;
using Web_TracNghiem_HTSV.Data;
using Web_TracNghiem_HTSV.Models;
using Web_TracNghiem_HTSV.Services;

namespace Web_TracNghiem_HTSV.Controllers
{
    [Authorize]
    public class TestsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TestsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> MoreDetailOfTest(string id)
        {
            // Giải mã `TestId` từ Base64
            var deCodeId = EncodeUrl.Decode(id);

            if (string.IsNullOrEmpty(deCodeId))
            {
                return NotFound();
            }

            // Lấy dữ liệu từ cơ sở dữ liệu
            var resultDetails = await _context.TestResults
                .Where(tr => tr.TestId == deCodeId)
                .Join(
                    _context.Users,
                    tr => tr.UserId,
                    u => u.Id,
                    (tr, u) => new { tr, u }
                )
                .GroupBy(t => new { t.tr.UserId, t.u.UserName, t.tr.TestId })
                .Select(g => new
                {
                    UserId = g.Key.UserId,
                    UserName = g.Key.UserName,
                    TestId = g.Key.TestId,
                    TotalScore = g.Sum(t => t.tr.TotalScore),
                    TimeTaken = g.Sum(t => EF.Functions.DateDiffSecond(t.tr.StartedAt, t.tr.SubmittedAt)),
                    LatestSubmittedAt = g.Max(t => t.tr.SubmittedAt)
                })
                .ToListAsync();

            // Chuyển đổi dữ liệu và sắp xếp trong bộ nhớ
            var resultDetailsViewModel = resultDetails
                .Select(r => new UserTestResultDetailViewModel
                {
                    UserId = r.UserId,
                    UserName = r.UserName,
                    TestId = r.TestId,
                    TotalScore = r.TotalScore,
                    TimeTaken = TimeSpan.FromSeconds(r.TimeTaken),
                    LatestSubmittedAt = r.LatestSubmittedAt
                })
                .OrderByDescending(r => r.TotalScore) // Sắp xếp theo điểm số từ cao đến thấp
                .ThenBy(r => r.TimeTaken) // Nếu điểm số bằng nhau, sắp xếp theo thời gian làm bài từ thấp đến cao
                .ToList();

            if (resultDetailsViewModel == null || !resultDetailsViewModel.Any())
            {
                return NotFound("Không tìm thấy kết quả làm bài cho bài kiểm tra này.");
            }

            return View(resultDetailsViewModel);
        }



        [Authorize(Roles = "Administrators")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LockTest(string id)
        {
            var test = await _context.Tests.FindAsync(id);

            if (test == null)
            {
                return NotFound();
            }

            test.IsLocked = true; // Mở khóa bài test

            try
            {
                _context.Update(test);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TestExists(test.TestId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrators")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnlockTest(string id)
        {
            var test = await _context.Tests.FindAsync(id);

            if (test == null)
            {
                return NotFound();
            }

            test.IsLocked = false; // Mở khóa bài test

            try
            {
                _context.Update(test);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TestExists(test.TestId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }


        [Authorize]
        [Authorize(Roles = "Administrators")]

        public ActionResult ListTests()
        {
            // Lấy danh sách các bài Test
            var tests = _context.Tests.Include(t => t.TestResults).ToList(); // db là đối tượng DbContext của bạn

            // Lấy UserId của người dùng hiện tại (cần phải có xác thực người dùng)
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value; // Phương thức này tùy thuộc vào cách bạn xác thực người dùng

            // Chuẩn bị danh sách các ViewModel để truyền vào view
            List<TestViewModel> testViewModels = new List<TestViewModel>();

            foreach (var test in tests)
            {
                // Kiểm tra xem người dùng đã làm bài Test này chưa
                var testResult = test.TestResults.FirstOrDefault(tr => tr.UserId == userId);

                // Tạo ViewModel cho từng Test để truyền vào view
                var viewModel = new TestViewModel
                {
                    TestId = test.TestId,
                    TestName = test.TestName,
                    IsTestTaken = testResult != null
                };

                testViewModels.Add(viewModel);
            }

            return View(testViewModels);
        }

        [Authorize]
        public async Task<IActionResult> ResultOfTest(string id)
        {
            // Giải mã `TestId` từ Base64
            var deCodeId = EncodeUrl.Decode(id);

            if (string.IsNullOrEmpty(deCodeId))
            {
                return NotFound();
            }

            string userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            // Sử dụng IQueryable để truy vấn Test
            var testQuery = _context.Tests
                .Include(t => t.Questions)
                    .ThenInclude(q => q.Answers)
                .Where(t => t.TestId == deCodeId)
                .AsQueryable();

            var test = await testQuery.FirstOrDefaultAsync();

            if (test == null)
            {
                return NotFound("Bài kiểm tra không tồn tại hoặc bạn chưa làm bài này.");
            }

            // Truy vấn TestResults bằng IQueryable
            var userTestResultsQuery = _context.TestResults
                .Where(tr => tr.TestId == deCodeId && tr.UserId == userId)
                .Include(tr => tr.User)
                .AsQueryable();

            var userTestResults = await userTestResultsQuery.ToListAsync();

            // Tính toán thời gian làm bài
            var earliestSubmittedResult = await userTestResultsQuery.MinAsync(tr => tr.StartedAt);
            var latestSubmittedResult = await userTestResultsQuery.MaxAsync(tr => tr.SubmittedAt);

            TimeSpan? timeTaken = latestSubmittedResult - earliestSubmittedResult;

            // Thiết lập ViewBag cho view
            ViewBag.TimeTaken = timeTaken;
            ViewBag.LatestSubmittedAt = latestSubmittedResult;
            ViewBag.UserTestResulted = userTestResults;
            ViewBag.UserId = userId;
            ViewBag.TestName = test.TestName;
            ViewBag.TotalScore = userTestResults.Sum(tr => tr.TotalScore);
            ViewBag.ListQuestion = test.Questions.ToList();
            ViewBag.ListTestResult = userTestResults;

            return View(test);
        }




        // TestsController.cs

        [Authorize]
        [Authorize(Roles = "Administrators")]
        public async Task<IActionResult> SelectTest()
        {
            var tests = await _context.Tests.ToListAsync(); // Lấy danh sách các bài test từ database
            return View(tests);
        }

        [Authorize]
        [HttpGet]
        public IActionResult TestDetails(string id, int page = 1)
        {
            // Giải mã `TestId` từ Base64
            var deCodeId = EncodeUrl.Decode(id);
            // Lưu thời gian bắt đầu vào Session nếu chưa có
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("TestStartTime")))
            {
                HttpContext.Session.SetString("TestStartTime", DateTime.UtcNow.ToString());
            }

            // Lấy thông tin bài test từ database
            var test = _context.Tests
                .Include(t => t.Questions)
                .ThenInclude(q => q.Answers)
                .FirstOrDefault(t => t.TestId == deCodeId);

            string userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var userMakeTestResult = _context.TestResults.Where(tr => tr.TestId == deCodeId && tr.UserId == userId).ToList();
            var questionOfTest = _context.Questions.Where(q => q.TestId == deCodeId).ToList();

            if (questionOfTest.Count == userMakeTestResult.Count())
            {

                return NotFound("Bạn đã làm bài này rồi");
           /*     return RedirectToAction("ResultOfTest", new { id = id });*/
            }
            if (test == null)
            {
                return NotFound();
            }
            if (test.IsLocked)
            {
                return NotFound("Bài kiểm tra đã bị khóa"); 
            }
            // Phân trang các câu hỏi
            int PageSize = 1;
            var questions = test.Questions
                .OrderBy(q => q.QuestionId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize)
                .ToList();

Views/Tests/Create.cshtml
@model Web_TracNghiem_HTSV.Models.Test

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Test</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="TestId" class="control-label"></label>
                <input asp-for="TestId" class="form-control" />
                <span asp-validation-for="TestId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TestName" class="control-label"></label>
                <input asp-for="TestName" class="form-control" />
                <span asp-validation-for="TestName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsLocked" /> @Html.DisplayNameFor(model => model.IsLocked)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tests/Delete.cshtml
@model Web_TracNghiem_HTSV.Models.Test

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Test</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TestName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TestName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsLocked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsLocked)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TestId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Tests/Details.cshtml
@model Web_TracNghiem_HTSV.Models.Test

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Test</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TestName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TestName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsLocked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsLocked)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TestId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Tests/Edit.cshtml
@model Web_TracNghiem_HTSV.Models.Test

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Test</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TestId" />
            <div class="form-group">
                <label asp-for="TestName" class="control-label"></label>
                <input asp-for="TestName" class="form-control" />
                <span asp-validation-for="TestName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsLocked" /> @Html.DisplayNameFor(model => model.IsLocked)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tests/ListTests.cshtml
@model List<TestViewModel>

<h2>Danh sách các bài Test</h2>

<table class="table">
    <thead>
        <tr>
            <th>Test Name</th>
            <th>IsLocked</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var test in Model)
        {
            <tr>
                <td>@test.TestName</td>
                <td>@test.IsLocked</td>
                <td>
                    @if (User.IsInRole("Administrators") && test.IsLocked)
                    {
                        <form asp-action="ToggleLock" asp-route-id="@test.TestId" method="post">
                            <button type="submit" class="btn btn-warning">Unlock</button>
                        </form>
                    }
                    else
                    {
                        @if (test.IsLocked == false)
                        {
                            @if (test.IsTestTaken)
                            {
                                <a asp-action="ResultOfTest" asp-route-id="@test.TestId" class="btn btn-primary">Xem kết quả</a>
                            }
                            else
                            {
                                <a asp-action="TestDetails" asp-route-id="@test.TestId" class="btn btn-success">Bắt đầu làm bài</a>
                            }
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Tests/MoreDetailOfTest.cshtml
@model IEnumerable<UserTestResultDetailViewModel>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Results</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        .rank-badge {
            color: #b45309; /* Màu chữ vàng đậm */
            font-weight: bold;
            padding: 0.25rem 0.5rem;
            border-radius: 9999px;
            font-size: 2rem;
            line-height: 1.25rem;
        }

            .rank-badge.gold {
                background-color: #ffd700; /* Màu nền vàng đậm */
                color: #fff; /* Màu chữ trắng */
            }
    </style>
    <script>
        function confirmDelete(event) {
            event.preventDefault(); // Ngăn chặn hành động submit mặc định
            var form = event.target.closest('form'); // Lấy form gần nhất
            if (confirm("Bạn có chắc chắn muốn xóa kết quả này?")) {
                form.submit(); // Nếu người dùng chọn OK, gửi form
            }
        }
    </script>
</head>
<body>
    <div class="container mx-auto">
        <h1 class="text-4xl font-bold mb-8 text-center text-blue-600">Kết quả</h1>
        @if (Model.Any())
        {
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-300 bg-white shadow-lg rounded-lg border border-gray-300">
                    <thead class="bg-blue-500 text-white rounded-t-lg">
                        <tr>
                            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">Hạng</th>
                            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">Người làm bài</th>
                            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">Tổng điểm</th>
                            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">Thời gian làm bài</th>
                            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">Nộp bài lúc</th>
                            <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider">Chức năng</th>
                        </tr>
                    </thead>
                    @{
                        var rank = 1;
                    }
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach (var result in Model)
                        {
                            <tr class="hover:bg-gray-100 transition duration-300 ease-in-out">
                                <td class="px-6 py-4 text-sm text-gray-900">
                                    @if (rank == 1)
                                    {
                                        <span class="rank-badge">🥇</span>
                                    }
                                    @if (rank > 1)
                                    {
                                        <span class="pl-6">@rank</span>
                                    }
                                </td>
                                <td class="px-6 py-4 text-sm text-gray-900">
                                    @result.UserName.Substring(0, result.UserName.IndexOf("@"))
                                </td>
                                <td class="px-6 py-4 text-sm text-gray-900">
                                    @result.TotalScore điểm
                                </td>
                                <td class="px-6 py-4 text-sm text-gray-900">
                                    @(result.TimeTaken.HasValue ? $"{result.TimeTaken.Value.TotalSeconds} giây" : "N/A")
                                </td>
                                <td class="px-6 py-4 text-sm text-gray-900">
                                    @(result.LatestSubmittedAt.HasValue ? result.LatestSubmittedAt.Value.ToString("HH:mm:ss (dd/MM/yyyy)") : "N/A")
                                </td>
                                <td class="px-6 py-4 text-sm text-gray-900">
                                    <form asp-controller="TestResults" asp-action="DeleteByUser" method="post" class="inline" onsubmit="confirmDelete(event)">
                                        <input type="hidden" value="@result.UserId" name="userId">
                                        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 ml-2">
                                            Hủy kết quả
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            rank++;
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5" class="px-6 py-4 text-center text-sm text-gray-700">
                                Xếp hạng bài kiểm tra
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        }
        else
        {
            <p class="text-center text-red-600">Không có kết quả để hiển thị.</p>
        }
    </div>
</body>
</html>

Views/Tests/SelectTest.cshtml
@model List<Web_TracNghiem_HTSV.Models.Test>

@{
    ViewBag.Title = "Select Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Select Test</h1>

<div class="container mx-auto p-4 sm:p-8">
    @foreach (var test in Model)
    {
        <div class="bg-white shadow-md rounded-lg p-6 mb-8 quiz-card">
            <h3 class="mb-4 text-lg font-bold">Test: @test.TestName</h3>
            <a class="text-blue-500" asp-action="TestDetails" asp-route-id="@test.TestId">Start Test</a>
        </div>
    }
</div>